FROM node:16-alpine as build
WORKDIR /app
COPY . /app/
RUN npm ci
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist  /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]